### PR TITLE
Add auto chest close thingy

### PR DESCRIPTION
**Pull request by HackerHansen**

### CODE REVIEW

**Comment by NRGJobro** [comment]
Yooooooooooooooooooo

**Comment by NRGJobro** [comment]
This is actually a good idea. I made it a rllyt scuffed way and this would be cleaner thx

**Comment by Intoprelised** [comment]
Nice

**Comment by NRGJobro** [comment]
ay @HackerHansen this for some reason makes the screen black when closing, and im not sure why.

**Comment by HackerHansen** [comment]
That's weird, it didn't do that in my testing. Does it still close the chest?

**Comment by HackerHansen** [comment]
Also it might be worth mentioning that you call the function 56 times lol

**Comment by HackerHansen** [comment]
Oh, I think I know why, you're closing the chest before the for loop exits so the chest manager is gone by the time the for loop finishes @NRGJobro

**Comment by NRGJobro** [comment]
Thats so true. I currently an not working on the project at this time and ill keep working on it tomorrow, or later, but if you want to fix that issue i had, then feel free to open a purr request @HackerHansen.

**Pull request merged**
