### PR TITLE
hacks removed, (commented out)

### PR DESCRIPTION
**Pull request by FoxGaal**
just the client without the cheats

### CODE REVIEW

**Comment by Intoprelised** [comment]
Perfect Pull, thanks for making our hacked client have errors and not have hacks! Appreciate it man! 😄

**Comment by FoxGaal** [comment]
I don't understand, it says no issues found

**Comment by FoxGaal** [comment]
note - I didn't know what a pull was this request was a mistake

**Comment by zPearlss** [comment]
Bruh, its a hacked client. its supposed to have the hacks. idk why but u removed them. bruh you serious?

**Pull request closed without merging**
