### PR TITLE
Removed things giving errors temporaraly. Like spinning in spin attack

### PR DESCRIPTION
**Pull request by NRGJobro**
Yes

### CODE REVIEW

**Comment by NRGJobro** [comment]
Just made arraylist colors look segsy

**Comment by Intoprelised** [comment]
its cus we cant access the functions from Actor even tho its inheriting

**Comment by NRGJobro** [comment]
REALLLY. Thx intop. I had no idea

**Comment by Intoprelised** [comment]
nvm i know how to fix

**Comment by zPearlss** [comment]
The LocalPlayer VTable is currently broken (i think), it will prob crash ur game when ur trying to use it.

**Comment by Intoprelised** [comment]
The only good thing in this pull is colors

**Pull request closed without merging**
