### PR TITLE
Crash

### PR DESCRIPTION
**Pull request by telecomadm1145**
CI sig did't work in my minecraft client(1.17.41),so it crashed.

### CODE REVIEW

**Comment by Intoprelised** [comment]
It should work

**Comment by Intoprelised** [comment]
Whats the issue?

**Comment by telecomadm1145** [comment]
CI sig didn't work.I looked at the code near CI with CE and found that the middle part of the function was hooked. Maybe CI sig isn't right for my MCBE?
QQ截图20211129182032
QQ截图20211129182051
QQ截图20211129182122
QQ截图20211129182248
QQ截图20211129182345
QQ截图20211129182421
QQ截图20211129182450
QQ截图20211129182535

**Comment by Laamy** [comment]
You need to build as x64 bit in release mode

**Comment by Laamy** [comment]
also your on the wrong minecraft version. its 1.18 - 1.18.1

**Pull request closed without merging**
