### PR TITLE
Better Jetpack

### PR DESCRIPTION
**Pull request by DRAGKILLS**
better than the old

### CODE REVIEW

**Comment by Intoprelised** [comment]
Good but could use improvement bec some directions r slower

**Comment by Intoprelised** [comment]
**IF you know how to fix that, if not say so**

**Comment by NRGJobro** [comment]
If possible, check out the slight glitch that at a certain angle, it will make you slower. If you cant fix that, then thats completly fine. But if you can, then open another pull.

**Comment by Laamy** [comment]
I know how to fix it

**Pull request merged**
